spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory-service

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.format_sql: true
    generate-ddl: false